<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('clinicos', function (Blueprint $table) {
            $table->id();
            $table->date("fecha")->nullable();
            $table->date("fecha_1vez")->nullable();
            $table->time("hora")->nullable();
            $table->boolean('imComplicado')->nullable();
            $table->date("imAnterior")->nullable();
            $table->date("imSeptal")->nullable();
            $table->date("imApical")->nullable();
            $table->date("imLateral")->nullable();
            $table->date("imInferior")->nullable();
            $table->date("imdelVD")->nullable();
            $table->date("anginaInestabale")->nullable();
            $table->date("anginaEstabale")->nullable();
            $table->date("choque_card")->nullable();
            $table->date("m_subita")->nullable();
            $table->double("clase_f_ccs")->nullable();
            $table->boolean("falla_cardiaca")->nullable();
            $table->boolean("sobreviviente_cpr")->nullable();
            $table->boolean("incapacidad_entrenar")->nullable();
            $table->double("cf_nyha")->nullable();
            $table->date("crvc")->nullable();
            $table->string("crvc_hemoductos")->nullable();
            $table->boolean("insuficiencia_art_per")->nullable();
            $table->boolean("v_mitral")->nullable();
            $table->boolean("v_aortica")->nullable();
            $table->boolean("v_tricuspide")->nullable();
            $table->boolean("v_pulmonar")->nullable();
            $table->boolean("congenitos")->nullable();
            $table->date("estratificacion")->nullable();
            $table->date("inicio_fase_2")->nullable();
            $table->date("fin_fase_2")->nullable();
            $table->boolean("tabaquismo")->nullable();
            $table->double("cig_dia")->nullable();
            $table->double("cig_years")->nullable();
            $table->boolean("cig_abandono")->nullable();
            $table->double("cig_años_abandono")->nullable();
            $table->double("hipertension_años")->nullable();
            $table->double("dm_years")->nullable();
            $table->boolean("actividad_fis")->nullable();
            $table->string("tipo_actividad")->nullable();
            $table->double("actividad_hrs_smn")->nullable();
            $table->double("actividad_years")->nullable();
            $table->double("actividad_abadono_years")->nullable();
            $table->double("estres_years")->nullable();
            $table->double("ansiedad_years")->nullable();
            $table->double("depresion_years")->nullable();
            $table->double("hipercolesterolemia_y")->nullable();
            $table->double("hipertrigliceridemia_y")->nullable();
            $table->double("diabetes_y")->nullable();
            $table->string("tiempo_evolucion")->nullable();
            $table->string("tratamiento")->nullable();
            $table->date("fecha_tra")->nullable();
            $table->string("betabloqueador")->nullable();
            $table->string("nitratos")->nullable();
            $table->string("calcioantagonista")->nullable();
            $table->string("aspirina")->nullable();
            $table->string("anticoagulacion")->nullable();
            $table->string("iecas")->nullable();
            $table->string("atii")->nullable();
            $table->string("diureticos")->nullable();
            $table->string("estatinas")->nullable();
            $table->string("fibratos")->nullable();
            $table->string("digoxina")->nullable();
            $table->string("antiarritmicos")->nullable();
            $table->string("otros")->nullable();
            $table->date("bh_fecha")->nullable();
            $table->double("hb")->nullable();
            $table->double("leucos")->nullable();
            $table->double("plaquetas")->nullable();
            $table->date("qs")->nullable();
            $table->double("glucosa")->nullable();
            $table->double("creatinina")->nullable();
            $table->double("ac_unico")->nullable();
            $table->double("colesterol")->nullable();
            $table->double("ldl")->nullable();
            $table->double("hdl")->nullable();
            $table->double("trigliceridos")->nullable();
            $table->double("tp")->nullable();
            $table->double("inr")->nullable();
            $table->double("tpt")->nullable();
            $table->double("pcras")->nullable();
            $table->double("otro_lab")->nullable();
            $table->date("ecg_fecha")->nullable();
            $table->string("ritmo")->nullable();
            $table->double("r_r_mm")->nullable();
            $table->double("fc_ecog")->nullable();
            $table->double("aP")->nullable();
            $table->double("aQRS")->nullable();
            $table->double("aT")->nullable();
            $table->double("duracion_qrs")->nullable();
            $table->double("duracion_p")->nullable();
            $table->double("qtm")->nullable();
            $table->double("qtc")->nullable();
            $table->double("pr")->nullable();
            $table->double("bav")->nullable();
            $table->boolean("brihh")->nullable();
            $table->boolean("brdhh")->nullable();
            $table->boolean("q_as")->nullable();
            $table->boolean("q_inf")->nullable();
            $table->boolean("q_lat")->nullable();
            $table->string("otros_ecg")->nullable();
            $table->date("eco_fecha")->nullable();
            $table->double("fe_por")->nullable();
            $table->double("dd_por")->nullable();
            $table->double("ds_por")->nullable();
            $table->string("trivi_por")->nullable();
            $table->double("rel_e_a")->nullable();
            $table->string("otros_eco")->nullable();
            $table->date("mn_fecha")->nullable();
            $table->double("fe_por_mn")->nullable();
            $table->boolean("ant_im")->nullable();
            $table->boolean("ant_isq")->nullable();
            $table->boolean("ant_rr")->nullable();
            $table->boolean("sept_im")->nullable();
            $table->boolean("sept_isq")->nullable();
            $table->boolean("sept_rr")->nullable();
            $table->boolean("lat_im")->nullable();
            $table->boolean("lat_isq")->nullable();
            $table->boolean("lat_rr")->nullable();
            $table->boolean("inf_im")->nullable();
            $table->boolean("inf_isq")->nullable();
            $table->boolean("inf_rr")->nullable();
            $table->boolean("vrie")->nullable();
            $table->date("vrie_fcha")->nullable();
            $table->double("fevi_basal")->nullable();
            $table->double("fevi_10_dobuta")->nullable();
            $table->double("reserva_inot_absolut")->nullable();
            $table->double("reserva_inot_relat")->nullable();
            $table->string("vrie_otros")->nullable();
            $table->string("vrie_riesgo")->nullable();
            $table->boolean("holter")->nullable();
            $table->date("holter_fecha")->nullable();
            $table->string("holter_dignostico")->nullable();
            $table->string("holter_riesgo")->nullable();
            $table->boolean("cateterismo")->nullable();
            $table->date("catet_fecha")->nullable();
            $table->double("catet_fe")->nullable();
            $table->double("catet_d2vi")->nullable();
            $table->double("catet_tco")->nullable();
            $table->string("catet_da_prox")->nullable();
            $table->string("catet_da_med")->nullable();
            $table->string("catet_da_dist")->nullable();
            $table->double("catet_1a_d")->nullable();
            $table->double("catet_2a_d")->nullable();
            $table->string("catet_cx_prox")->nullable();
            $table->double("catet_cx_dist")->nullable();
            $table->double("catet_om")->nullable();
            $table->double("catet_pl")->nullable();
            $table->string("catet_cd_aprox")->nullable();
            $table->string("catet_cd_med")->nullable();
            $table->string("catet_cd_dist")->nullable();
            $table->double("catet_r_vent_izq")->nullable();
            $table->double("catet_dp")->nullable();
            $table->string("catet_otros")->nullable();
            $table->string("catet_movilidad")->nullable();
            $table->string("catet_riesgo")->nullable();
            $table->boolean("termino")->nullable();
            $table->double("semanas")->nullable();
            $table->boolean("aprendio_borg")->nullable();
            $table->boolean("muerte")->nullable();
            $table->boolean("inestabilidad_cardio")->nullable();
            $table->boolean("hospitalizacion")->nullable();
            $table->boolean("susp_motu_propio")->nullable();
            $table->boolean("lesion_osteo")->nullable();
            $table->boolean("res_otros")->nullable();
            $table->date("era_vez_fecha")->nullable();
            $table->string("sintomas")->nullable();
            $table->double("dasi")->nullable();
            $table->boolean("comer_vestirse")->nullable();
            $table->boolean("caminar_casa")->nullable();
            $table->boolean("caminar_2_cuadras")->nullable();
            $table->boolean("subir_piso")->nullable();
            $table->boolean("correr_corta")->nullable();
            $table->boolean("lavar_trastes")->nullable();
            $table->boolean("aspirar_casa")->nullable();
            $table->boolean("trapear")->nullable();
            $table->boolean("jardineria")->nullable();
            $table->boolean("relaciones")->nullable();
            $table->boolean("jugar")->nullable();
            $table->boolean("deportes_extenuantes")->nullable();
            $table->string("TA")->nullable();
            $table->double("fc")->nullable();
            $table->string("exploracion_fisica")->nullable();
            $table->string("estudios")->nullable();
            $table->string("diagnostico_general")->nullable();
            $table->string("plan")->nullable();
            $table->foreignId('user_id')->constrained()->onDelete('cascade');
            $table->foreignId('paciente_id')->constrained()->onDelete('cascade');
            $table->integer('tipo_exp')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('clinicos');
    }
};
