<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('esfuerzos', function (Blueprint $table) {
            $table->id();
            $table->string('numPrueba')->nullable();
            $table->date('fecha')->nullable();
            $table->boolean('icc')->nullable();
            $table->integer('FEVI')->nullable();
            $table->string('metodo')->nullable();
            $table->boolean('disfuncionDias')->nullable();
            $table->boolean('nyha')->nullable();
            $table->integer('ccs')->nullable();
            $table->boolean('betabloqueador')->nullable();
            $table->boolean('iecas')->nullable();
            $table->boolean('nitratos')->nullable();
            $table->boolean('digoxina')->nullable();
            $table->boolean('calcioAntag')->nullable();
            $table->boolean('antirritmicos')->nullable();
            $table->boolean('hipolipemiantes')->nullable();
            $table->boolean('diureticos')->nullable();
            $table->boolean('aldactone')->nullable();
            $table->boolean('antiagregante')->nullable();
            $table->boolean('otros')->nullable();
            $table->double('prevalencia')->nullable();
            $table->boolean('confusor')->nullable();
            $table->double('sensibilidad')->nullable();
            $table->double('especificidad')->nullable();
            $table->double('vpp')->nullable();
            $table->double('vpn')->nullable();
            $table->boolean('pruebaIngreso')->nullable();
            $table->boolean('pruebaFinFase2')->nullable();
            $table->boolean('pruebaFinFase3')->nullable();
            $table->date('fechaDeInicio')->nullable();
            $table->boolean('balke')->nullable();
            $table->boolean('bruce')->nullable();
            $table->boolean('ciclo')->nullable();
            $table->boolean('banda')->nullable();
            $table->boolean('medicionGases')->nullable();
            $table->double('fcBasal')->nullable();
            $table->double('tasBasal')->nullable();
            $table->double('tadBasal')->nullable();
            $table->double('dapBasal')->nullable();
            $table->double('fcBorg12')->nullable();
            $table->double('tasBorg12')->nullable();
            $table->double('tadBorg12')->nullable();
            $table->double('dpBorg12')->nullable();
            $table->double('w_50')->nullable();
            $table->double('fc_w_50')->nullable();
            $table->double('tas_w_50')->nullable();
            $table->double('tad_w_50')->nullable();
            $table->double('borg_w_50')->nullable();
            $table->double('dp_w_50')->nullable();
            $table->double('fcMax')->nullable();
            $table->double('tasMax')->nullable();
            $table->double('tadMax')->nullable();
            $table->double('borgMax')->nullable();
            $table->double('tAMax_tAbasal')->nullable();
            $table->double('tAMax_tAbasal_val')->nullable();
            $table->double('tiempoEsfuerzo')->nullable();
            $table->double('dpMax')->nullable();
            $table->string('motivoSuspension')->nullable();
            $table->boolean('pba_submax')->nullable();
            $table->boolean('fc_mayor_50')->nullable();
            $table->double('fc_1er_min')->nullable();
            $table->double('tas_1er_min')->nullable();
            $table->double('tad_1er_min')->nullable();
            $table->double('borg_1er_min')->nullable();
            $table->double('dp_1er_min')->nullable();
            $table->double('fc_3er_min')->nullable();
            $table->double('tas_3er_min')->nullable();
            $table->double('tad_3er_min')->nullable();
            $table->double('borg_3er_min')->nullable();
            $table->double('dp_3er_min')->nullable();
            $table->double('fc_5to_min')->nullable();
            $table->double('tas_5to_min')->nullable();
            $table->double('tad_5to_min')->nullable();
            $table->double('fc_8vo_min')->nullable();
            $table->double('tas_8vo_min')->nullable();
            $table->double('tad_8vo_min')->nullable();
            $table->double('fc_U_isq')->nullable();
            $table->double('tas_U_isq')->nullable();
            $table->double('tad_U_isq')->nullable();
            $table->double('borg_U_isq')->nullable();
            $table->double('scoreAngina')->nullable();
            $table->boolean('arritmias')->nullable();
            $table->string('tipoArritmias')->nullable();
            $table->boolean('positiva')->nullable();
            $table->string('tipoCambioElectrico')->nullable();
            $table->double('MaxInfra')->nullable();
            $table->double('veteranos')->nullable();
            $table->double('duke')->nullable();
            $table->string('riesgo')->nullable();
            $table->double('u_isq_borg')->nullable();
            $table->double('u_isq_dp')->nullable();
            $table->double('vel_borg_12')->nullable();
            $table->double('inclin_borg_12')->nullable();
            $table->double('watts_ciclo_b_12')->nullable();
            $table->double('vel_max')->nullable();
            $table->double('incl_max')->nullable();
            $table->double('watts_ciclo_max')->nullable();
            $table->double('vel_um_isq')->nullable();
            $table->double('incl_um_isq')->nullable();
            $table->double('watts_ciclo_u_isq')->nullable();
            $table->double('vo2_max_gases')->nullable();
            $table->double('vo2_pico_gases')->nullable();
            $table->double('vo2_borg_gases')->nullable();
            $table->double('r_qmax')->nullable();
            $table->double('umbral_aeer_anaer')->nullable();
            $table->double('po2_teor')->nullable();
            $table->double('fc_max_calc')->nullable();
            $table->double('fc_85')->nullable();
            $table->double('fc_max_alcanzado')->nullable();
            $table->double('vo2t_mujer')->nullable();
            $table->double('mets_teorico_mujer')->nullable();
            $table->double('vo2t_varon')->nullable();
            $table->double('mets_teorico_varon')->nullable();
            $table->double('mets_teorico_general')->nullable();
            $table->double('vo2r_borg_12')->nullable();
            $table->double('mets_banda_borg_12')->nullable();
            $table->double('mets_ciclo_b12')->nullable();
            $table->double('mets_gases_b12')->nullable();
            $table->double('mets_borg_12')->nullable();
            $table->double('vo2r_max')->nullable();
            $table->double('mets_banda_max')->nullable();
            $table->double('mets_ciclo_max')->nullable();
            $table->double('mets_gases_max')->nullable();
            $table->double('mets_max')->nullable();
            $table->double('vo2_alcanzado')->nullable();
            $table->double('vo2r_U_isq')->nullable();
            $table->double('mets_banda_U_isq')->nullable();
            $table->double('mets_ciclo_U_isq')->nullable();
            $table->double('mets_U_isq')->nullable();
            $table->double('mvo2')->nullable();
            $table->double('mvo2_mets')->nullable();
            $table->double('iem')->nullable();
            $table->double('po2t_mujer')->nullable();
            $table->double('po2t_varon')->nullable();
            $table->double('po2tr')->nullable();
            $table->double('rfa_mujer')->nullable();
            $table->double('rfa_varon')->nullable();
            $table->double('resp_presora')->nullable();
            $table->double('indice_tas')->nullable();
            $table->double('resp_crono')->nullable();
            $table->double('fcmax_fc1er')->nullable();
            $table->double('fcmax_fc3er')->nullable();
            $table->double('fc_rec_1_por')->nullable();
            $table->double('fc_rec_3_por')->nullable();
            $table->double('pbp3')->nullable();
            $table->double('pce')->nullable();
            $table->double('tce')->nullable();
            $table->double('vel_borg_12_mh')->nullable();
            $table->double('vel_max_mh')->nullable();
            $table->double('vel_u_isq_mh')->nullable();
            $table->double('ch_borg_12')->nullable();
            $table->double('ch_max')->nullable();
            $table->double('ch_u_isq')->nullable();
            $table->double('cv_borg_12')->nullable();
            $table->double('cv_max')->nullable();
            $table->double('cv_u_isq')->nullable();
            $table->string('conclusiones')->nullable();
            $table->foreignId('user_id')->constrained()->onDelete('cascade');
            $table->foreignId('paciente_id')->constrained()->onDelete('cascade');
            $table->integer('tipo_exp')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('esfuerzos');
    }
};
