<?php

/**
 * Plantillas de consentimiento informado dental.
 * Basadas en NOM-013-SSA2-2015 (Apéndice B / numeral 9.6.9) y buenas prácticas clínicas.
 * El texto es orientativo; el odontólogo debe adaptar diagnóstico y plan al caso.
 */
return [
    'plantillas' => [
        'general' => [
            'clave' => 'general',
            'titulo' => 'Consentimiento informado odontológico (general)',
            'procedimiento_default' => 'Atención odontológica y procedimiento(s) indicado(s) en el plan de tratamiento',
            'descripcion' => 'Formato general para procedimientos dentales con anestesia local.',
            'objetivos' => 'Diagnosticar, tratar y/o prevenir alteraciones de la salud bucal según el plan acordado, buscando aliviar molestias, restaurar función y/o mejorar la salud oral.',
            'beneficios' => 'Mejoría del estado bucal, reducción de dolor o infección, conservación o rehabilitación de piezas dentales, y disminución del riesgo de complicaciones futuras si se siguen las indicaciones.',
            'riesgos' => [
                'Dolor, inflamación o sensibilidad temporal después del procedimiento.',
                'Hemorragia leve o hematomas en tejidos blandos.',
                'Infección local que puede requerir antibióticos o atención adicional.',
                'Reacciones a la anestesia local (poco frecuentes): mareo, alergia, hematoma o parestesia temporal.',
                'Necesidad de tratamiento complementario si el tejido o la pieza no responden como se esperaba.',
            ],
            'alternativas' => 'Observación clínica, tratamiento farmacológico sintomático, remisión a otro especialista, o no realizar el procedimiento (con los riesgos del padecimiento sin tratar).',
            'sin_tratamiento' => 'El padecimiento puede persistir o agravarse (dolor, infección, pérdida dental, afectación de tejidos vecinos o necesidad de tratamientos más invasivos).',
        ],
        'extraccion' => [
            'clave' => 'extraccion',
            'titulo' => 'Consentimiento informado — Extracción dental',
            'procedimiento_default' => 'Extracción dental (exodoncia) de la(s) pieza(s) indicada(s)',
            'descripcion' => 'Extracción simple o quirúrgica de piezas dentales.',
            'objetivos' => 'Retirar la(s) pieza(s) dental(es) indicada(s) para eliminar infección, dolor, movilidad irreversible, o como parte de un plan quirúrgico/ortodóntico.',
            'beneficios' => 'Alivio del dolor o infección, eliminación de pieza no recuperable y facilitación de un plan de rehabilitación posterior (prótesis, implante u ortodoncia) cuando aplique.',
            'riesgos' => [
                'Dolor, inflamación, equimosis y dificultad para abrir la boca de forma temporal.',
                'Hemorragia persistente o alveolitis (“alveolo seco”).',
                'Infección del sitio quirúrgico.',
                'Lesión de tejidos vecinos, fractura de raíz o de hueso alveolar.',
                'Comunicación bucosinusal (en piezas superiores posteriores) que puede requerir manejo adicional.',
                'Parestesia temporal o, raramente, persistente por cercanía a nervios (especialmente molares inferiores).',
                'Reacciones adversas a anestesia local o medicamentos prescritos.',
            ],
            'alternativas' => 'Tratamiento de conductos (si la pieza es recuperable), corona/restauración, antibiótico y seguimiento, o remisión a cirugía maxilofacial.',
            'sin_tratamiento' => 'Puede progresar la infección, el dolor, el absceso, la destrucción ósea o la afectación de piezas y tejidos adyacentes.',
        ],
        'endodoncia' => [
            'clave' => 'endodoncia',
            'titulo' => 'Consentimiento informado — Endodoncia (tratamiento de conductos)',
            'procedimiento_default' => 'Tratamiento de conductos (endodoncia) de la pieza indicada',
            'descripcion' => 'Limpieza, desinfección y obturación de conductos radiculares.',
            'objetivos' => 'Conservar la pieza dental eliminando el tejido pulpar inflamado o infectado y sellando los conductos para controlar la infección.',
            'beneficios' => 'Alivio del dolor, control de infección y posibilidad de conservar la pieza con restauración posterior (poste/corona cuando se indique).',
            'riesgos' => [
                'Dolor o sensibilidad postoperatoria por varios días.',
                'Instrumentación incompleta por anatomía compleja; posible necesidad de retratamiento o cirugía apical.',
                'Fractura de instrumento dentro del conducto.',
                'Perforación radicular o extrusión de material irrigante/obturador.',
                'Cambio de coloración de la corona dental.',
                'Fracaso del tratamiento que derive en extracción.',
                'Reacciones a anestesia o medicamentos.',
            ],
            'alternativas' => 'Extracción de la pieza, observación (si asintomática y de bajo riesgo), o remisión a endodoncista.',
            'sin_tratamiento' => 'Puede persistir o agravarse el dolor, formarse absceso, perderse hueso de soporte y eventualmente la pieza.',
        ],
        'cirugia' => [
            'clave' => 'cirugia',
            'titulo' => 'Consentimiento informado — Cirugía bucal menor',
            'procedimiento_default' => 'Cirugía bucal menor (terceros molares, quistes menores, frenectomía u otro procedimiento indicado)',
            'descripcion' => 'Procedimientos quirúrgicos orales bajo anestesia local.',
            'objetivos' => 'Resolver patología quirúrgica oral (piezas retenidas, lesiones, frenillos u otras indicaciones) para restaurar función y prevenir complicaciones.',
            'beneficios' => 'Eliminación de la causa del problema, reducción de episodios infecciosos y mejora de la función o higiene según el caso.',
            'riesgos' => [
                'Dolor, inflamación, hematomas y limitación de apertura bucal.',
                'Hemorragia e infección del sitio quirúrgico.',
                'Lesión nerviosa temporal o permanente (labio, lengua, mentón).',
                'Daño a piezas o restauraciones vecinas.',
                'Comunicación bucosinusal o problemas de cicatrización.',
                'Necesidad de reintervención o manejo hospitalario en complicaciones graves (poco frecuente).',
                'Efectos de la anestesia local y de la medicación postoperatoria.',
            ],
            'alternativas' => 'Manejo conservador, diferir la cirugía, o remisión a cirujano maxilofacial / medio hospitalario.',
            'sin_tratamiento' => 'La patología puede progresar (infección recurrente, quistes, daño a piezas vecinas o mayor complejidad quirúrgica futura).',
        ],
        'implante' => [
            'clave' => 'implante',
            'titulo' => 'Consentimiento informado — Implante dental',
            'procedimiento_default' => 'Colocación de implante dental oseointegrado y etapas asociadas del plan',
            'descripcion' => 'Colocación de implante(s) y rehabilitación protésica relacionada.',
            'objetivos' => 'Reemplazar pieza(s) ausente(s) con un implante que permita rehabilitación fija o removible estable.',
            'beneficios' => 'Mejor función masticatoria y estética, preservación ósea relativa y alternativa a prótesis removible convencional.',
            'riesgos' => [
                'Inflamación, hematomas y molestias postquirúrgicas.',
                'Infección periimplantaria o fracaso de oseointegración.',
                'Lesión de nervios o estructuras anatómicas vecinas (seno maxilar, nervio dentario).',
                'Necesidad de injerto óseo o regeneración adicional.',
                'Aflojamiento, fractura de componentes o pérdida del implante.',
                'Resultado estético o funcional distinto al esperado.',
                'Reacciones a anestesia o materiales.',
            ],
            'alternativas' => 'Prótesis removible, puente fijo convencional, no rehabilitar el espacio, o diferir el tratamiento.',
            'sin_tratamiento' => 'Puede haber pérdida ósea progresiva, migración de piezas vecinas y deterioro de la función masticatoria/estética.',
        ],
        'ortodoncia' => [
            'clave' => 'ortodoncia',
            'titulo' => 'Consentimiento informado — Tratamiento de ortodoncia',
            'procedimiento_default' => 'Tratamiento ortodóntico (brackets, alineadores u aparatología indicada)',
            'descripcion' => 'Corrección de maloclusiones y alineación dental.',
            'objetivos' => 'Mejorar alineación, oclusión y/o estética dental mediante aparatología activa y controles periódicos.',
            'beneficios' => 'Mejor higiene, función oclusal, estética y, en algunos casos, prevención de desgaste o problemas articulares asociados a maloclusión.',
            'riesgos' => [
                'Molestias, úlceras o sensibilidad al inicio y tras ajustes.',
                'Descalcificaciones o caries si la higiene es insuficiente.',
                'Reabsorción radicular leve a moderada.',
                'Recidiva si no se usan retenedores según indicación.',
                'Lesión gingival, aflojamiento de brackets/aditamentos o necesidad de extracciones auxiliares.',
                'Duración o resultado distinto al estimado inicialmente.',
                'En casos complejos, posible necesidad de cirugía ortognática (se informaría por separado).',
            ],
            'alternativas' => 'No tratar, camuflaje protésico/estético limitado, o remisión a ortodoncista/cirugía.',
            'sin_tratamiento' => 'La maloclusión puede mantenerse o agravarse, con impacto en higiene, estética, desgaste dental o función.',
        ],
    ],
];
